// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

#nullable disable

namespace UTaskManager.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.UserTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserTaskId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("UserTasks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            CreatedAt = new DateTime(2024, 12, 11, 15, 42, 43, 8, DateTimeKind.Local).AddTicks(8593),
                            Deadline = new DateTime(2024, 12, 25, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "TestDescription1",
                            Priority = 1,
                            Status = 1,
                            Title = "TestTitle1",
                            UpdatedAt = new DateTime(2024, 12, 11, 15, 42, 43, 10, DateTimeKind.Local).AddTicks(5310)
                        },
                        new
                        {
                            Id = new Guid("3d490a70-94ce-4d15-9494-5248280c2ce3"),
                            CreatedAt = new DateTime(2024, 12, 11, 15, 42, 43, 10, DateTimeKind.Local).AddTicks(5515),
                            Deadline = new DateTime(2025, 12, 25, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "TestDescription2",
                            Priority = 2,
                            Status = 0,
                            Title = "TestTitle2",
                            UpdatedAt = new DateTime(2024, 12, 11, 15, 42, 43, 10, DateTimeKind.Local).AddTicks(5517)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
